[workspace]
resolver = "3"
members = ["packages/aist-core", "packages/aist-spec"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
homepage = "https://github.com/DenisGorbachev/aist"
repository = "https://github.com/DenisGorbachev/aist"
keywords = []
categories = []
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "AGENTS.ts",
    "CargoMetadata.ts",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.lock",
    "deno.json",
    "commitlint.config.mjs",
    "fnox.toml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    ".yolobox"
]

[workspace.metadata.details]
name = "aist"
title = ""
readme = { generate = false }

[workspace.lints.rust]
redundant_imports = "deny"
unused_import_braces = "deny"
# unused_qualifications must not be "deny" because our code style has multiple `use Foo::*;`, and some macros (derive_more::Display, strum::Display, strum::EnumString) produce code with full qualifications
# unused_qualifications = "deny"

[workspace.lints.clippy]
absolute_paths = "deny"
arithmetic_side_effects = "deny"

[workspace.dependencies]
aist-core = { version = "0.1.0", path = "packages/aist-core" }
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive", "env"] }
errgonomic = { git = "https://github.com/DenisGorbachev/errgonomic" }
ra_ap_hir = "0.0.349"
ra_ap_ide_db = "0.0.349"
ra_ap_load-cargo = "0.0.349"
ra_ap_proc_macro_api = "0.0.349"
ra_ap_project_model = "0.0.349"
ra_ap_syntax = "0.0.349"
ra_ap_vfs = "0.0.349"
save-load = { git = "https://github.com/DenisGorbachev/save-load", features = ["clap", "serde_json", "serde_yaml", "toml"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.53.1", features = ["macros", "rt", "rt-multi-thread"] }

[package]
name = "aist"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[package.metadata.details]
title = ""

[lints]
workspace = true

[dependencies]
aist-core.workspace = true
clap.workspace = true
errgonomic.workspace = true
ra_ap_hir.workspace = true
ra_ap_ide_db.workspace = true
ra_ap_syntax.workspace = true
ra_ap_vfs.workspace = true
save-load.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
